### ISSUE TITLE
RandLA-Net OpenGF training.

### ISSUE THREAD

**Issue by coding-encoding** [Nathan-UW/OpenGF#2]
Hi, thanks for your impressive work. In the paper, the RandLA-Net method achieved an accuracy of 94% in both Test 1 and Test 2, while my results are much lower, with an F1-Score of 90% and 78% respectively. So, I want to know more details about how you trained this dataset using RandLA-Net. Do you use other attributes like intensity, return number, or something else? Thanks again for your wonderful work.

**Comment by Nathan-UW** [comment]
"Since none of these DL-based pipelines was tailored for the GF task, some minor modifications were introduced to make them
adapt better to the OpenGF dataset". Only the XYZ coordinates were used. To get more information, please see our new paper https://www.sciencedirect.com/science/article/abs/pii/S0924271623001703?via%3Dihub
